const CHANGE_USER_STATE_TRUE = 'CHANGE_USER_STATE_TRUE';
const CHANGE_USER_STATE_FALSE = 'CHANGE_USER_STATE_FALSE';
// const USER_PRESSED_TRUE = 'USER_PRESSED_TRUE';
// const USER_PRESSED_FALSE = 'USER_PRESSED_FALSE';


export {CHANGE_USER_STATE_TRUE, CHANGE_USER_STATE_FALSE};